// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD19CJhrnsfyyMk6CiYtvG5f1ccYWOlsgA',
    appId: '1:731163949244:web:42f0047646bdbe652eb8b9',
    messagingSenderId: '731163949244',
    projectId: 'daily-earning-tracker-2ae07',
    authDomain: 'daily-earning-tracker-2ae07.firebaseapp.com',
    storageBucket: 'daily-earning-tracker-2ae07.firebasestorage.app',
    measurementId: 'G-1NX3K2BP74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpx2iRiZACLqFXFfbP6yHxW3qkXlOGqIU',
    appId: '1:731163949244:android:1ba05916242faac22eb8b9',
    messagingSenderId: '731163949244',
    projectId: 'daily-earning-tracker-2ae07',
    storageBucket: 'daily-earning-tracker-2ae07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA32_W7L5Krjr-jbsyci8-3vWaiDQH_IOU',
    appId: '1:731163949244:ios:7255286f5f2fd6bb2eb8b9',
    messagingSenderId: '731163949244',
    projectId: 'daily-earning-tracker-2ae07',
    storageBucket: 'daily-earning-tracker-2ae07.firebasestorage.app',
    iosBundleId: 'com.example.dailyIncomeTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA32_W7L5Krjr-jbsyci8-3vWaiDQH_IOU',
    appId: '1:731163949244:ios:7255286f5f2fd6bb2eb8b9',
    messagingSenderId: '731163949244',
    projectId: 'daily-earning-tracker-2ae07',
    storageBucket: 'daily-earning-tracker-2ae07.firebasestorage.app',
    iosBundleId: 'com.example.dailyIncomeTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD19CJhrnsfyyMk6CiYtvG5f1ccYWOlsgA',
    appId: '1:731163949244:web:14e26248a102131e2eb8b9',
    messagingSenderId: '731163949244',
    projectId: 'daily-earning-tracker-2ae07',
    authDomain: 'daily-earning-tracker-2ae07.firebaseapp.com',
    storageBucket: 'daily-earning-tracker-2ae07.firebasestorage.app',
    measurementId: 'G-3LB2JQDL1L',
  );
}
